### ISSUE TITLE
Remove deprecated import

### ISSUE THREAD

**Issue by salents** [bioinf-jku/FCD#5]
The scipy 1.3.0 release removes `misc.imread`. 
See here for details: [GitHub](https://github.com/scipy/scipy/releases/tag/v1.3.0)

Adapt the import in `fcd.FCD`.

**Comment by msteijaert** [comment]
It seems sufficient to remove the "from scipy.misc import imread", as imread is not used anywhere in fcd.FCD

**Comment by renzph** [comment]
I removed all the unneeded imports.
